import = [ "~/.config/alacritty/catppuccin-macchiato.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 18
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }

[window.dimensions]
columns = 100
lines = 28

# [shell]
# program = "zellij"

[cursor]
blink_interval = 500
blink_timeout = 0
[cursor.style]
shape = "Block"
blinking = "Always"

[window]
# padding.x = 16
# padding.y = 14
decorations = "Full"
opacity = 1

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
